import { test, expect } from '@playwright/test';
import { replaceEditorSource } from './editor';

test('Monaco consumes current Aetheris Helix completion and keeps source editable', async ({ page }) => {
  const runtimeRequests: string[] = [];
  page.on('request', request => { if (request.url().includes('/aetheris-runtime')) runtimeRequests.push(request.url()); });
  await page.goto('/');
  await page.getByRole('button', { name: 'My Projects' }).click();
  await page.getByRole('button', { name: 'New to Helios? Create an account' }).click();
  await page.getByLabel('Name').fill('LX browser witness');
  await page.getByLabel('Email').fill(`lx-${Date.now()}@example.test`);
  await page.getByLabel('Password').fill('Correct-Helios-Password-2026');
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.getByRole('heading', { name: 'Your projects' })).toBeVisible();
  await page.getByLabel('Project name').fill('LX witness');
  const editorStart = performance.now();
  await page.getByRole('button', { name: 'Create project' }).click();
  await expect(page.locator('.monaco-editor')).toBeVisible();
  const editorVisibleMs = performance.now() - editorStart;
  await expect(page.locator('.status-ready')).toContainText('READY', { timeout: 120_000 });
  await page.locator('.monaco-editor .view-lines').click();
  await page.keyboard.press('ControlOrMeta+Shift+P');
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible();
  await page.keyboard.press('Escape');
  await page.locator('.monaco-editor .view-lines').click();
  await page.keyboard.press('ControlOrMeta+A');
  await page.keyboard.insertText('Model M { WireForm Spring { Helix Winding {\n    Rad');
  const helixRenderStart = performance.now();
  await page.keyboard.press('ControlOrMeta+Space');
  await expect(page.locator('.suggest-widget')).toContainText('Radius');
  const helixRenderMs = performance.now() - helixRenderStart;
  await expect(page.locator('.monaco-editor')).toContainText('Rad');
  const helixMs = await page.evaluate(() => performance.getEntriesByName('helios-lx-complete').at(-1)?.duration ?? -1);
  await page.keyboard.press('Escape');
  await page.keyboard.press('ControlOrMeta+A');
  await page.keyboard.insertText('Model M { Loft<Hollow> Body {\n    Thi');
  await page.keyboard.press('ControlOrMeta+Space');
  await expect(page.locator('.suggest-widget')).toContainText('Thickness');
  const loftMs = await page.evaluate(() => performance.getEntriesByName('helios-lx-complete').at(-1)?.duration ?? -1);
  console.log(`LX browser timings: editor visible ${editorVisibleMs.toFixed(1)} ms, Helix SDK ${helixMs.toFixed(1)} ms, Loft SDK ${loftMs.toFixed(1)} ms, Helix suggestion visible ${helixRenderMs.toFixed(1)} ms`);
  await page.locator('input[type="file"]').setInputFiles({ name: 'selector.firmament', mimeType: 'text/plain', buffer: Buffer.from('Model SelectorWitness {\n Units: mm\n Box Body { Size: [30mm, 20mm, 10mm] }\n}\n') });
  await expect(page.locator('.bottom-tabs')).toContainText('selector.firmament');
  await expect(page.locator('.status-ready')).toContainText('READY', { timeout: 120_000 });
  await expect(page.locator('.statusbar')).toContainText('1 DEFS');
  await page.locator('.monaco-editor .view-lines').click();
  await page.keyboard.press('ControlOrMeta+End');
  await page.keyboard.insertText('\nface(');
  await page.keyboard.press('ControlOrMeta+Space');
  await expect(page.locator('.suggest-widget')).toContainText('face(+Z)');
  await page.locator('.suggest-widget').getByText('face(+Z)', { exact: true }).dblclick();
  await expect(page.locator('.view-lines')).toContainText('face(+Z)');
  await page.locator('input[type="file"]').setInputFiles({ name: 'hole-selector.firmament', mimeType: 'text/plain', buffer: Buffer.from('Model HoleWitness {\n Units: mm\n Box Body { Size: [30mm, 20mm, 10mm] }\n Modify Body { Hole<Shaft> H { On: +Z Center: Point2(0mm, 0mm) Diameter: 10mm End: ThroughAll } }\n}\n') });
  await expect(page.locator('.bottom-tabs')).toContainText('hole-selector.firmament');
  await expect(page.locator('.status-ready')).toContainText('READY', { timeout: 120_000 });
  await page.locator('.monaco-editor .view-lines').click();
  await page.keyboard.press('ControlOrMeta+End');
  await page.keyboard.insertText('\nface(');
  const selectorStart = performance.now();
  await page.keyboard.press('ControlOrMeta+Space');
  await expect(page.locator('.suggest-widget')).toContainText('face(H.Wall)');
  console.log(`LX selector suggestion visible ${ (performance.now() - selectorStart).toFixed(1) } ms`);
  await page.keyboard.press('Escape');
  await replaceEditorSource(page, 'Model Bad {\n Box Body { Size: [30mm, 20mm, 10mm] \n}\n');
  const diagnosticStart = performance.now();
  await page.keyboard.press('ControlOrMeta+Enter');
  await expect(page.locator('.statusbar')).toContainText('1 DIAGNOSTICS');
  await expect(page.locator('.statusbar')).toContainText('1 DEFS');
  await expect(page.locator('.statusbar')).toContainText('MODEL OUT OF DATE');
  await expect(page.locator('.squiggly-error')).toHaveCount(1);
  await page.getByRole('button', { name: /PROBLEMS/ }).click();
  await expect(page.locator('.diagnostic-list .diagnostic')).toHaveCount(1);
  await page.locator('.diagnostic-list .diagnostic').click();
  await expect(page.getByRole('textbox', { name: 'Editor content' })).toBeFocused();
  console.log(`LX rebuild diagnostic and navigation ${ (performance.now() - diagnosticStart).toFixed(1) } ms`);
  if (new URL(page.url()).port === '4174') {
    expect(runtimeRequests.some(url => url.includes('/aetheris-runtime/_framework/dotnet.native.'))).toBe(true);
    expect(runtimeRequests.some(url => url.includes('/aetheris-runtime-aot/_framework/dotnet.native.'))).toBe(true);
  }
});
