import { test, expect } from '@playwright/test';

test('Helix Worker build leaves Monaco, palette, view, save and heartbeat live', async ({ page, context }) => {
  test.setTimeout(240_000);
  const runtimeRequests: string[] = [];
  page.on('request', request => { if (request.url().includes('/aetheris-runtime')) runtimeRequests.push(request.url()); });
  await page.goto('/');
  await page.getByRole('button', { name: 'My Projects' }).click();
  await page.getByRole('button', { name: 'New to Helios? Create an account' }).click();
  await page.getByLabel('Name').fill('Worker Witness');
  await page.getByLabel('Email').fill(`worker-${Date.now()}@example.test`);
  await page.getByLabel('Password').fill('Correct-Helios-Password-2026');
  await page.getByRole('button', { name: 'Create account' }).click();
  await expect(page.getByRole('heading', { name: 'Your projects' })).toBeVisible();
  await page.getByLabel('Project name').fill('Worker witness');
  await page.getByRole('button', { name: 'Create project' }).click();
  await expect(page.locator('.status-ready')).toContainText('READY', { timeout: 120_000 });
  await expect(page.locator('.statusbar')).toContainText('WASM Worker');
  await page.evaluate(() => {
    const samples: number[] = [];
    let previous = performance.now();
    const timer = setInterval(() => { const now = performance.now(); samples.push(now - previous); previous = now; }, 50);
    Object.assign(window, { workerHeartbeat: { samples, timer } });
  });
  await page.getByRole('button', { name: /Command Palette/ }).click();
  await page.getByLabel('Search commands').fill('Helix');
  await page.getByRole('button', { name: /New Helix Model/ }).click();
  const staleBuildStarted = Date.now();
  await expect(page.locator('.status-ready')).toContainText('Building', { timeout: 10_000 });
  const paletteStart = Date.now();
  await page.getByRole('button', { name: /Command Palette/ }).click();
  await expect(page.getByRole('dialog', { name: 'Command palette' })).toBeVisible();
  const paletteMs = Date.now() - paletteStart;
  await page.keyboard.press('Escape');
  const typingStart = Date.now();
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  await page.evaluate(() => navigator.clipboard.writeText('\n// edited while worker builds'));
  await page.locator('.monaco-editor .view-lines').click();
  await page.keyboard.press('ControlOrMeta+End');
  await page.keyboard.press('ControlOrMeta+V');
  await expect(page.locator('.view-lines')).toContainText('edited while worker builds');
  const typingMs = Date.now() - typingStart;
  await page.getByRole('button', { name: 'TOP', exact: true }).click();
  await expect(page.locator('.statusbar')).toContainText('ORTHOGRAPHIC');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await expect(page.locator('.cloud-save-state')).toContainText('Saved');
  await expect(page.locator('.status-ready')).toContainText('READY', { timeout: 120_000 });
  const staleBuildMs = Date.now() - staleBuildStarted;
  await expect(page.locator('.statusbar')).toContainText('MODEL OUT OF DATE');
  const heartbeat = await page.evaluate(() => {
    const value = (window as unknown as { workerHeartbeat: { samples: number[]; timer: number } }).workerHeartbeat;
    clearInterval(value.timer);
    return { count: value.samples.length, maxGapMs: Math.max(...value.samples) };
  });
  expect(heartbeat.count).toBeGreaterThan(10);
  expect(heartbeat.maxGapMs).toBeLessThan(2000);
  expect(paletteMs).toBeLessThan(2000);
  expect(typingMs).toBeLessThan(2000);
  const currentBuildStarted = Date.now();
  await page.getByRole('button', { name: '↻ Rebuild' }).click();
  await expect(page.locator('.status-ready')).toContainText('READY', { timeout: 120_000 });
  const currentBuildMs = Date.now() - currentBuildStarted;
  await expect(page.locator('.statusbar')).not.toContainText('MODEL OUT OF DATE');
  await expect(page.locator('.statusbar')).toContainText('1 DEFS');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export STEP', exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe('helix.step');
  const displayUpdates = await page.evaluate(() => performance.getEntriesByName('helios-display-update').map(item => item.duration));
  const phaseStatus = await page.locator('[title="Last successful Worker build phases"]').textContent();
  if (new URL(page.url()).port === '4174')
    expect(runtimeRequests.some(url => url.includes('/aetheris-runtime-aot/_framework/dotnet.native.'))).toBe(true);
  console.log('WORKER_HELIX_RESPONSIVENESS', JSON.stringify({ paletteMs, typingMs, staleBuildMs, currentBuildMs, displayUpdates, phaseStatus, ...heartbeat }));
});
