import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { fakeModel, ok } from '../test/fakes';
import { helixModelSource } from '../commands/sourceAuthoring';

const { runtimeMock } = vi.hoisted(() => ({ runtimeMock: { info: { packageVersion: '2.0.0-preview.3' }, initialize: vi.fn(), restart: vi.fn(), open: vi.fn(), schema: vi.fn(), describeConstruct: vi.fn(), rewriteField: vi.fn(), setSource: vi.fn(), setProperty: vi.fn(), rebuild: vi.fn(), exportSTEP: vi.fn(), dispose: vi.fn(), session: vi.fn() } }));
vi.mock('../sdk/CadRuntime', () => ({ WebSdkCadRuntime: class { constructor() { return runtimeMock; } } }));
vi.mock('../viewport/Viewport', () => ({ Viewport: ({ onSelect }: { onSelect(id: string, face: string): void }) => <button data-testid="viewport" onClick={() => onSelect('box:plate', 'face:top')}>Viewport geometry</button> }));

import { HeliosApp } from './HeliosApp';
const model = fakeModel({ sourceName: 'editable-bracket.firmament' });

describe('Helios IDE shell', () => {
  beforeEach(() => { localStorage.clear(); vi.clearAllMocks(); vi.stubGlobal('URL', { ...URL, createObjectURL: vi.fn(() => 'blob:helios-test'), revokeObjectURL: vi.fn() }); vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined); runtimeMock.open.mockResolvedValue({ model, diagnostics: [] }); runtimeMock.restart.mockResolvedValue(runtimeMock.info); runtimeMock.schema.mockResolvedValue({ version: 'firmament-semantic-schema/1', constructs: [{ id: 'Helix', entry: helixModelSource }] }); runtimeMock.describeConstruct.mockRejectedValue(new Error('No projection in fake model')); runtimeMock.setSource.mockResolvedValue(ok()); runtimeMock.setProperty.mockResolvedValue(ok()); runtimeMock.rebuild.mockResolvedValue(ok()); runtimeMock.exportSTEP.mockResolvedValue(new Uint8Array([1])); runtimeMock.session.mockImplementation(() => runtimeMock.open.mock.calls.length ? model : null); });
  it('shows the active file in the explorer', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); expect(screen.getByRole('region', { name: 'Project explorer' })).toHaveTextContent('editable-bracket.firmament'); expect(screen.queryByRole('region', { name: 'Model browser' })).not.toBeInTheDocument(); });
  it('persists Sirius', async () => { render(<HeliosApp />); fireEvent.change(screen.getByLabelText('Theme'), { target: { value: 'sirius' } }); await waitFor(() => expect(localStorage.getItem('helios-theme')).toBe('sirius')); });
  it('reveals semantic face identity from viewport selection', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByTestId('viewport')); expect(screen.getByText('Plate', { selector: '.entity-hero strong' })).toBeVisible(); expect(screen.getByText('face:top', { selector: 'dd' })).toBeVisible(); });
  it('inserts a valid box from the palette', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByRole('button', { name: /Command Palette/ })); fireEvent.change(screen.getByLabelText('Search commands'), { target: { value: 'insert box' } }); fireEvent.click(screen.getByRole('button', { name: /Insert Box/ })); expect((screen.getByLabelText('Firmament source') as HTMLTextAreaElement).value).toContain('Box HeliosBox1 { Size: [30mm, 20mm, 10mm] }'); });
  it('opens a compilable Helix source from the palette', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByRole('button', { name: /Command Palette/ })); fireEvent.change(screen.getByLabelText('Search commands'), { target: { value: 'helix' } }); fireEvent.click(screen.getByRole('button', { name: /New Helix Model/ })); await waitFor(() => expect(runtimeMock.open).toHaveBeenLastCalledWith(expect.stringContaining('Helix Winding'), 'helix.firmament', expect.any(Number))); expect((screen.getByLabelText('Firmament source') as HTMLTextAreaElement).value).toContain('WireForm Spring'); });
  it('rebuilds changed source through the SDK session', async () => { render(<HeliosApp />); const source = await screen.findByLabelText('Firmament source'); fireEvent.change(source, { target: { value: 'Model Changed {}' } }); fireEvent.click(screen.getByText('↻ Rebuild')); await waitFor(() => expect(runtimeMock.setSource).toHaveBeenCalledWith('Model Changed {}', 'editable-bracket.firmament', expect.any(Number))); });
  it('exports STEP through the palette', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByRole('button', { name: /Command Palette/ })); fireEvent.click(within(screen.getByRole('dialog', { name: 'Command palette' })).getByRole('button', { name: 'Export STEP' })); await waitFor(() => expect(runtimeMock.exportSTEP).toHaveBeenCalledOnce()); });
  it('exposes Worker restart after a transport failure', async () => { runtimeMock.open.mockRejectedValueOnce(new Error('worker died')); render(<HeliosApp />); fireEvent.click(await screen.findByRole('button', { name: 'Restart Worker' })); await waitFor(() => expect(runtimeMock.restart).toHaveBeenCalledOnce()); await waitFor(() => expect(screen.getByRole('status').textContent).toContain('READY')); });
});
