import { fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { fakeModel, ok } from '../test/fakes';

const { runtimeMock } = vi.hoisted(() => ({ runtimeMock: { info: { packageVersion: '2.0.0-preview.3' }, initialize: vi.fn(), open: vi.fn(), setSource: vi.fn(), setProperty: vi.fn(), rebuild: vi.fn(), exportSTEP: vi.fn(), dispose: vi.fn(), session: vi.fn() } }));
vi.mock('../sdk/CadRuntime', () => ({ WebSdkCadRuntime: class { constructor() { return runtimeMock; } } }));
vi.mock('../viewport/Viewport', () => ({ Viewport: ({ onSelect }: { onSelect(id: string, face: string): void }) => <button data-testid="viewport" onClick={() => onSelect('box:plate', 'face:top')}>Viewport geometry</button> }));

import { HeliosApp } from './HeliosApp';
const model = fakeModel();

describe('Helios IDE shell', () => {
  beforeEach(() => { localStorage.clear(); vi.clearAllMocks(); vi.stubGlobal('URL', { ...URL, createObjectURL: vi.fn(() => 'blob:helios-test'), revokeObjectURL: vi.fn() }); vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => undefined); runtimeMock.open.mockResolvedValue({ model, diagnostics: [] }); runtimeMock.setSource.mockResolvedValue(ok()); runtimeMock.setProperty.mockResolvedValue(ok()); runtimeMock.rebuild.mockResolvedValue(ok()); runtimeMock.exportSTEP.mockResolvedValue(new Uint8Array([1])); runtimeMock.session.mockReturnValue(model); });
  it('shows the active file in the explorer', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); expect(screen.getByRole('region', { name: 'Project explorer' })).toHaveTextContent('editable-bracket.firmament'); expect(screen.queryByRole('region', { name: 'Model browser' })).not.toBeInTheDocument(); });
  it('persists Sirius', async () => { render(<HeliosApp />); fireEvent.change(screen.getByLabelText('Theme'), { target: { value: 'sirius' } }); await waitFor(() => expect(localStorage.getItem('helios-theme')).toBe('sirius')); });
  it('reveals semantic face identity from viewport selection', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByTestId('viewport')); expect(screen.getByText('Plate', { selector: '.entity-hero strong' })).toBeVisible(); expect(screen.getByText('face:top', { selector: 'dd' })).toBeVisible(); });
  it('navigates from selected geometry to its SDK source range', async () => { const nodes = model.tree.nodes.map(node => node.id === 'box:plate' ? { ...node, source: { source: 'editable-bracket.firmament', line: 3, column: 5, start: 44, length: 9 } } : node); const located = fakeModel({ tree: { ...model.tree, nodes }, entity: id => nodes.find(node => node.id === id) }); runtimeMock.open.mockResolvedValue({ model: located, diagnostics: [] }); render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByTestId('viewport')); fireEvent.click(screen.getByRole('button', { name: 'Go to Source' })); await waitFor(() => expect((screen.getByLabelText('Firmament source') as HTMLTextAreaElement).selectionStart).toBe(44)); });
  it('selects matching geometry when the source cursor enters an SDK range', async () => { const nodes = model.tree.nodes.map(node => node.id === 'box:plate' ? { ...node, source: { source: 'editable-bracket.firmament', line: 3, column: 5, start: 44, length: 9 } } : node); runtimeMock.open.mockResolvedValue({ model: fakeModel({ tree: { ...model.tree, nodes }, entity: id => nodes.find(node => node.id === id) }), diagnostics: [] }); render(<HeliosApp />); const editor = await screen.findByLabelText('Firmament source') as HTMLTextAreaElement; editor.setSelectionRange(46, 46); fireEvent.keyUp(editor, { key: 'ArrowRight' }); expect(screen.getByText('Plate', { selector: '.entity-hero strong' })).toBeVisible(); });
  it('inserts a valid box from the palette', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByRole('button', { name: /Command Palette/ })); fireEvent.change(screen.getByLabelText('Search commands'), { target: { value: 'insert box' } }); fireEvent.click(screen.getByRole('button', { name: /Insert Box/ })); expect((screen.getByLabelText('Firmament source') as HTMLTextAreaElement).value).toContain('Box HeliosBox1 { Size: [30mm, 20mm, 10mm] }'); });
  it('opens a compilable Helix source from the palette', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByRole('button', { name: /Command Palette/ })); fireEvent.change(screen.getByLabelText('Search commands'), { target: { value: 'helix' } }); fireEvent.click(screen.getByRole('button', { name: /New Helix Model/ })); await waitFor(() => expect(runtimeMock.open).toHaveBeenLastCalledWith(expect.stringContaining('Helix Winding'), 'helix.firmament')); expect((screen.getByLabelText('Firmament source') as HTMLTextAreaElement).value).toContain('WireForm Spring'); });
  it('rebuilds changed source through the SDK session', async () => { render(<HeliosApp />); const source = await screen.findByLabelText('Firmament source'); fireEvent.change(source, { target: { value: 'Model Changed {}' } }); fireEvent.click(screen.getByText('↻ Rebuild')); await waitFor(() => expect(runtimeMock.setSource).toHaveBeenCalledWith('Model Changed {}', 'editable-bracket.firmament')); });
  it('exports STEP through the palette', async () => { render(<HeliosApp />); await waitFor(() => expect(runtimeMock.open).toHaveBeenCalled()); fireEvent.click(screen.getByRole('button', { name: /Command Palette/ })); fireEvent.click(within(screen.getByRole('dialog', { name: 'Command palette' })).getByRole('button', { name: 'Export STEP' })); await waitFor(() => expect(runtimeMock.exportSTEP).toHaveBeenCalledOnce()); });
});
